addSbtPlugin("org.typelevel"     % "sbt-catalysts"  % "0.40")
addSbtPlugin("com.47deg"         % "sbt-microsites" % "1.2.1")
addSbtPlugin("com.eed3si9n"      % "sbt-unidoc"     % "0.4.3")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"   % "3.9.4")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"        % "2.0.1")
addSbtPlugin("com.github.gseitz" % "sbt-release"    % "1.0.13")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"   % "2.4.2")
